# Generated by Django 2.1.15 on 2021-12-13 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarPark',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100)),
            ],
            options={
                'db_table': 'CarPark',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('fio', models.CharField(blank=True, db_column='Fio', max_length=150)),
                ('sal', models.IntegerField(blank=True, db_column='Salary', null=True)),
                ('park_id', models.ForeignKey(db_column='Park_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='main.CarPark')),
            ],
            options={
                'db_table': 'Driver',
            },
        ),
        migrations.CreateModel(
            name='DriverPark',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('driver_id', models.ForeignKey(db_column='Driver_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Driver')),
                ('park_id', models.ForeignKey(db_column='Park_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='main.CarPark')),
            ],
            options={
                'db_table': 'DriverPark',
            },
        ),
    ]
