# Generated by Django 2.1.15 on 2021-12-13 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=30)),
                ('frequency', models.CharField(blank=True, db_column='Frequency', max_length=10, null=True)),
                ('architecture', models.CharField(blank=True, db_column='Architecture', max_length=20, null=True)),
            ],
            options={
                'db_table': 'CPU',
            },
        ),
        migrations.CreateModel(
            name='Diskstorage',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('type', models.CharField(db_column='Type', max_length=20)),
                ('rs', models.CharField(blank=True, db_column='RS', max_length=20, null=True)),
                ('ws', models.CharField(blank=True, db_column='WS', max_length=20, null=True)),
                ('volume', models.CharField(db_column='Volume', max_length=20)),
            ],
            options={
                'db_table': 'DiskStorage',
            },
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cpu', models.ForeignKey(db_column='CPU_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Cpu')),
                ('diskstor', models.ForeignKey(db_column='DiskStor_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Diskstorage')),
            ],
            options={
                'db_table': 'Hardware',
            },
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('type', models.CharField(db_column='Type', max_length=20)),
                ('frequency', models.CharField(db_column='Frequency', max_length=20)),
                ('volume', models.SmallIntegerField(blank=True, db_column='Volume', null=True)),
            ],
            options={
                'db_table': 'RAM',
            },
        ),
        migrations.AddField(
            model_name='hardware',
            name='ram',
            field=models.ForeignKey(db_column='RAM_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Ram'),
        ),
    ]
